export const GET_GALLERY_IMAGE = 'GET_GALLERY_IMAGE';
export const SET_SORT_FILTER = 'SET_SORT_FILTER';
export const SET_WINDOW_FILTER = 'SET_WINDOW_FILTER';
export const SET_SECTION_FILTER = 'SET_SECTION_FILTER';
export const SET_VIRAL_FILTER = 'SET_VIRAL_FILTER';
