export const GET_CONTATC_START= 'GET_CONTATC_START';
export const GET_CONTATC_DATA= 'GET_CONTATC_DATA';
export const GET_CONTATC_ERROR= 'GET_CONTATC_ERROR';
export const SEARCH_CONTATC= "SEARCH_CONTATC";
