export const GET_THREADS_START= 'GET_THREADS_START';
export const GET_THREADS_DATA= 'GET_THREADS_DATA';
export const GET_THREADS_ERROR= 'GET_THREADS_ERROR';
export const SEARCH_THREADS= "SEARCH_THREADS";